### ISSUE TITLE
[BUG] ibruce和watermark enable设为false后控制台报错

### ISSUE THREAD

**Issue by whuwangyong** [Lruihao/FixIt#114]
### Describe the bug 描述你遇到的错误

![image](https://user-images.githubusercontent.com/5968678/163508027-4c20af0e-8252-4250-9371-01f85e5f6cb9.png)
![image](https://user-images.githubusercontent.com/5968678/163508358-cfd22c17-beae-4c1d-aa6e-bb5b35cf75da.png)

改为true就没问题。

我的配置文件如下：
```yaml
  # Busuanzi count since v0.2.12
  # 不蒜子统计 since v0.2.12
  [params.ibruce]
    enable = false
    # Enable in post meta
    # 在文章中开启
    enablePost = true
    # Site creation time
    # 网站创立时间
    siteTime = '2021-12-18T16:15:22+08:00'

  [params.watermark]
    enable = false

```

即使用主题自带的exampleSite测试也是这样。

**Comment by Lruihao** [comment]
已修复

**Comment by whuwangyong** [comment]
大佬神速
