### ISSUE TITLE
hugo 加密研究

### ISSUE THREAD

**Issue by Lruihao** [Lruihao/FixIt#123]
hugo 加密研究，希望提供前端解决方案，不依赖 python 或者 golang

## Feature

- [x] 全文加密 frontmatter 提供 password, message
- [x] shortcode 提供部分加密

## 注意事项

- 文章源码不能公开（GitInfo 将获取失败）
- 关掉加密文章的 markdown 文档输出

## 参考

- https://github.com/Li4n0/hugo_encryptor
- https://github.com/Izumiko/hugo-encrypt
- https://gist.github.com/tscholl2/dc7dc15dc132ea70a98e8542fefffa28#file-aes-js

**Comment by labulac** [comment]
有相同的加密需求，可以参考hexo插件  感谢作者辛苦付出

**Comment by Lruihao** [comment]
> 有相同的加密需求，可以参考hexo插件
> 
> 感谢作者辛苦付出


嗯嗯，尽可能在v0.2.14发布，最晚下个版本

**Comment by Lruihao** [comment]
:construction:

- [x] 英文解密
- [ ]  中文、emoji 解密
- [x] ondecrypted 钩子函数
- [x] 隐藏 TOC
- [ ] 隐藏 编辑此页等按钮
- [ ] 在搜索结果中隐藏
- [ ] 首页摘要增加判断 默认值提示 (i18n)
- [ ] 强制阻止 markdown 输出 (i18n)
- [ ] input UI (i18n)

**Comment by Lruihao** [comment]
全文加密功能已完成

**Comment by Lruihao** [comment]
部分加密 `fixit-encryptor` shortcode 已完成

（_`fixit-encryptor` 内使用其他组件及自身嵌套待后续优化_）

**Comment by Lruihao** [comment]
由于 Hugo 已提供的 [hash](https://gohugo.io/functions/hash/) 和 [crypto](https://gohugo.io/functions/crypto/) 函数中截止 Hugo v0.132.0 为止并没有类似 AES 的对称加密，所以，这个方案缺点很明显，加密部分确实很弱，请大家谨慎考虑使用该功能。 

---

### 后续优化

- https://github.com/hugo-fixit/FixIt/issues/492
