### ISSUE TITLE
[BUG] Current environment is "development". The "comment system", "CDN" and "fingerprint" will be disabled.

### ISSUE THREAD

**Issue by ericvlog** [Lruihao/FixIt#134]
### Describe the bug 描述你遇到的错误

hugo 已经是extended 版本了，还是报错。

C:\Users\Administrator\Desktop\Portable\PortableGit\blog\ericvlog>hugo version
hugo v0.98.0-165d299cde259c8b801abadc6d3405a229e449f6+extended windows/amd64 BuildDate=2022-04-28T10:23:30Z VendorInfo=gohugoio

C:\Users\Administrator\Desktop\Portable\PortableGit\blog\ericvlog>hugo server
Start building sites …
hugo v0.98.0-165d299cde259c8b801abadc6d3405a229e449f6+extended windows/amd64 BuildDate=2022-04-28T10:23:30Z VendorInfo=gohugoio
WARN 2022/05/11 23:23:46

Current environment is "development". The "comment system", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "CDN" 和 "fingerprint" 不会启用.

**Comment by Lruihao** [comment]
你提供的log没显示报错呀，只是提示开发环境不会启用评论等

**Comment by hiifong** [comment]
> 你提供的log没显示报错呀，只是提示开发环境不会启用评论等

好像只有生产环境才可以cdn和启用评论系统吧

**Comment by ericvlog** [comment]
> > 你提供的log没显示报错呀，只是提示开发环境不会启用评论等
> 
> 好像只有生产环境才可以cdn和启用评论系统吧

就是说在Windows 10 才会出现 ，当我推送到github pages 就没有问题了，可以用cdn 和 评论了是吗？
谢谢

**Comment by hiifong** [comment]
> 

嗯

**Comment by hiifong** [comment]
> > > 你提供的log没显示报错呀，只是提示开发环境不会启用评论等
> > 
> > 
> > 好像只有生产环境才可以cdn和启用评论系统吧
> 
> 就是说在Windows 10 才会出现 ，当我推送到github pages 就没有问题了，可以用cdn 和 评论了是吗？ 谢谢

嗯

**Comment by Lruihao** [comment]
本地可以指定开发或者生产环境 `--environment production `

生产环境才会启用评论 CDN 等

```
hugo server --disableFastRender --navigateToChanged --environment production
```
