### ISSUE TITLE
[FEATURE] 添加一个目录滚动

### ISSUE THREAD

**Issue by hiifong** [Lruihao/FixIt#136]
### Describe the feature you want 描述你的功能需求

![image](https://user-images.githubusercontent.com/89133723/168440010-b13ee9ee-7d40-40e8-8f37-603c0f1dda42.png)
希望添加一个目录单独滚动，如果目录过长，页面滑动目录不会跟随着标题自动定位，需要滑到文章触底才触发目录滑动。
效果见[https://52at.ml](https://52at.ml/vim/)

**Comment by Lruihao** [comment]
good idea!
我也发现这个问题了，打算下个版本处理的

**Comment by Lruihao** [comment]
已处理
