### ISSUE TITLE
[BUG] 移动端（手机）目录搜索栏无法输入文字

### ISSUE THREAD

**Issue by Sino-Huang** [Lruihao/FixIt#143]
### Describe the bug 描述你遇到的错误

如题，安卓手机 用 chrome 浏览器 和 egde 浏览器都不能在目录的搜索栏输入问题。

### Expected behavior 期待的行为

可以修复 手机端搜索栏无法输入文字的问题

### Build Environment 构建环境

- OS  Android 10

**Comment by Lruihao** [comment]
@Sino-Huang 能提供一下报错网址吗？

**Comment by Sino-Huang** [comment]
> @Sino-Huang 能提供一下报错网址吗？ 是搜索框无法输入还是无法搜索？

你好，是搜索框无法触发 输入法，可以粘贴问题，但是无法输入文字，
我是直接在 https://fixit.lruihao.cn/  浏览的时候发现的。
theme 很好看！

**Comment by Lruihao** [comment]
> > @Sino-Huang 能提供一下报错网址吗？ 是搜索框无法输入还是无法搜索？
> 
> 你好，是搜索框无法触发 输入法，可以粘贴问题，但是无法输入文字， 我是直接在 https://fixit.lruihao.cn/ 浏览的时候发现的。 theme 很好看！

我没有安卓手机，暂时无法复现，之后我找朋友试试

**Comment by Lruihao** [comment]
经确认，上诉问题确实存在，初步判断是滚动效果导致 header 自动收起

- Chrome 异常
- Edge 异常
- 部分自带浏览器 异常
- 微信内置浏览器 正常

**Comment by Lruihao** [comment]
已处理
