### ISSUE TITLE
Artalk 前端版本已过时，请更新以获得完整体验

### ISSUE THREAD

**Issue by RalstonLiu** [Lruihao/FixIt#150]
### Describe the feature you want 描述你的功能需求

首先感谢作者维护这么一款优秀的主题！目前刚折腾Hugo，正在使用中。

在搭建评论系统的时候，我自己在Docker上搭建了Artalk，对接到我们主题的时候，提示“Artalk 前端版本已过时，请更新以获得完整体验”，想请教一下，是否只需要更改一下引用的css即可？我没有找到在哪里修改 = =

![](https://img.laoda.de/i/2022/06/03/12r1quo-0.webp)

**Comment by Lruihao** [comment]
@RalstonLiu 用 CDN 的话，可以修改 CDN 配置文件的版本号，本地依赖待更新
https://github.com/Lruihao/FixIt/blob/master/assets/data/cdn/jsdelivr.yml#L17-L18

**Comment by Lruihao** [comment]
updated Artalk from 2.2.12 to 2.3.4
