### ISSUE TITLE
在标签主页或搜索结果下面加多标签筛选功能，筛选文章

### ISSUE THREAD

**Issue by userxiaosi** [Lruihao/FixIt#162]
### Describe the feature you want 描述你的功能需求

标签：
- 标签按特定排序规则，如字母顺序，方便快速定位标签。
- 标签横向排列，超过页面宽度时换行，但标签行超过5行时出现进度滚动条(像代码框那样)
- 标签选择可以随时增加或减少。如我现在选了A, B, C三个标签，我可以去除B标签选择或选择D标签减少搜索范围
- 标签会根据文章减少。如我现在选了A, B, C 三个标签，所筛选的文章中没有D标签，那标签集中不应该出现D标签，因为选中没用还认为是BUG，也能让使用者自检是否选错标签
- 要有一键取消所有标签选中功能

文章：
- 文章出现在标签选择的下方，像首页那样只展示标题、内容摘要（`summary`变量）
- 文章以新标签页面打开
- 文章排序优先级：
   1. 按标签关联度由高到低，关联度=(选中标签/文章标签)的占比。如选中A, B, C标签，文章只有A, B, C 标签关联度为100%，应该排第一
   2. 相同标签关联度按照更新时间排序，更新时间越旧通常是过期的。如选中A, C标签，文章1标签有A, C, D。文章2有A, C, F标签，它们的关联度相同，更新时间近的排前面

**Comment by userxiaosi** [comment]
这只是我的想法，没有在其它网站看到有使用。目前的标签功能已经满足使用了

**Comment by Lruihao** [comment]
> 这只是我的想法，没有在其它网站看到有使用。目前的标签功能已经满足使用了

对于静态页面来说，要实现这个可能需要建立一个很复杂的索引来关联这些 tag 的 url，如果 hugo 不提供相关的渲染支持，我不打算处理该功能。
