### ISSUE TITLE
[FEATURE] Sub menu

### ISSUE THREAD

**Issue by Lruihao** [Lruihao/FixIt#31]
- [Useful reference](https://codingnconcepts.com/hugo/nested-menu-hugo/)
- https://gohugo.io/content-management/menus/#readout
- https://gohugo.io/templates/menu-templates/
- https://getbootstrap.com/docs/5.1/examples/navbars/

**Comment by Lruihao** [comment]
@pandaoh 没事看看这个，怎么好看

**Comment by pandaoh** [comment]
> @pandaoh 没事看看这个，怎么好看

i see see

**Comment by Lruihao** [comment]
> > @pandaoh 没事看看这个，怎么好看
> 
> i see see

我打算和切换语言那个下拉框风格保持一致

**Comment by Lruihao** [comment]
resolved

**Comment by Lruihao** [comment]
resolved

**Comment by Lruihao** [comment]
TODO: revise documentation for sub menu

**Comment by Lruihao** [comment]
> TODO: revise documentation for sub menu

resolved the docs addition
