### ISSUE TITLE
[FEATURE] 添加Artalk评论系统

### ISSUE THREAD

**Issue by iuvhub** [Lruihao/FixIt#54]
https://github.com/ArtalkJS/Artalk
这个评论系统后端自建
![image](https://user-images.githubusercontent.com/89133723/151565292-07847cb1-1c70-4d6e-98c0-2632f982ff21.png)

**Comment by Lruihao** [comment]
马上过年了，预计年后处理

**Comment by iuvhub** [comment]
辛苦大佬了

**Comment by Lruihao** [comment]
[feature-artalk 分支](https://github.com/Lruihao/FixIt/tree/feature-artalk) 已合并你的PR，并做了优化，有空的话麻烦你测试一下，没问题我就合并到 `v0.2.13-RC`

**Comment by Lruihao** [comment]
![image](https://user-images.githubusercontent.com/33419593/151703449-4d560592-ecb2-4c3c-908d-1e28ae5b5c17.png)

**Comment by Lruihao** [comment]
![image](https://user-images.githubusercontent.com/33419593/151704433-2a184ebc-edaf-4013-b1a8-1097a04ebc25.png)
已自动调整 暗黑主题

**Comment by Lruihao** [comment]
:wrench: Merge branch 'feature-artalk' into v0.2.13-RC

**Comment by iuvhub** [comment]
> :wrench: Merge branch 'feature-artalk' into v0.2.13-RC, Thanks @iuvhub 

标题好像还是没有获取到![image](https://user-images.githubusercontent.com/89133723/151705171-1bf5ee45-4dd9-4dfd-8eba-9571beeacb31.png)

**Comment by iuvhub** [comment]
我当时通过`.Title`是可以直接获取的。

**Comment by Lruihao** [comment]
> 我当时通过`.Title`是可以直接获取的。

你在控制台输入 `this.config.comment.artalk`看看有没有包含 `pageKey` 和 `pageTitle`

没有的话，更新到 v0.2.13-RC 最新版，然后刷新浏览器缓存试试

**Comment by iuvhub** [comment]
> 

这个就是最新版本
![image](https://user-images.githubusercontent.com/89133723/151706406-9b5aac47-8eba-470d-864c-7fc209a90ffe.png)

**Comment by Lruihao** [comment]
> 这个就是最新版本
> 
> ![image](https://user-images.githubusercontent.com/89133723/151706406-9b5aac47-8eba-470d-864c-7fc209a90ffe.png)
> 
> 现在问题是什么？明天我仔细看看这两个参数的作用

**Comment by iuvhub** [comment]
> 
邮件里没有pageTitle和pageKey
![image](https://user-images.githubusercontent.com/89133723/151707011-d4ca68ed-1cf8-49ec-9a04-b14d876f5a3f.png)

**Comment by Lruihao** [comment]
@iuvhub 有空帮忙看看，现在可不可以

![image](https://user-images.githubusercontent.com/33419593/151731401-309b205c-0d42-482a-bf18-550e6cbc1237.png)

**Comment by iuvhub** [comment]
这是artalk的一个bug，当site的值为默认站点的话，才可以正常收到pageTitle，其他的就不行

**Comment by Lruihao** [comment]
> 这是artalk的一个bug，当site的值为默认站点的话，才可以正常收到pageTitle，其他的就不行

是 artalk 后端收不到吗，如果是 artalk 的bug 只能等他修复。

FixIt 目前设定是默认 pageKey 为页面链接，pageTitle 为页面标题。

**Comment by iuvhub** [comment]
> 

这是后端获取到的部分数据
![image](https://user-images.githubusercontent.com/89133723/151735134-0e41bd0a-4ff4-4dba-ad3c-646d9a53c01f.png)

**Comment by iuvhub** [comment]
> > 这是artalk的一个bug，当site的值为默认站点的话，才可以正常收到pageTitle，其他的就不行
> 
> 是 artalk 后端收不到吗，如果是 artalk 的bug 只能等他修复。
> 
> FixIt 目前设定是默认 pageKey 为页面链接，pageTitle 为页面标题。

应该是bug吧，我给他提issue了

**Comment by iuvhub** [comment]
> 

那可以先把site的默认值设为“默认站点”，这样就可以正常获取到pageTitle了

**Comment by Lruihao** [comment]
应该是你的后端配置问题，我用 artalk 官方的 API 测试,邮件内容都是正常的

![image](https://user-images.githubusercontent.com/33419593/151739361-d0b8d782-994f-49ec-a001-7bc6747489b4.png)
---
![image](https://user-images.githubusercontent.com/33419593/151739508-81346f63-fa8a-4bdc-be80-65438ea3e553.png)
