### ISSUE TITLE
[FEATURE] add lightbox for Artalk

### ISSUE THREAD

**Issue by iuvhub** [Lruihao/FixIt#59]
- Feature 1 add lightbox for Artalk
 [link](https://artalk.js.org/guide/frontend/lightbox.html#lightgallery)
![image](https://user-images.githubusercontent.com/89133723/151756156-884d2f93-224b-4cb0-87f2-c0ed0b7c6ab0.png)

**Comment by Lruihao** [comment]
done

**Comment by iuvhub** [comment]
> done
好像这个灯箱不起zuo y q

**Comment by Lruihao** [comment]
> 好像这个灯箱不起作用
> 你切到这个分支 (https://github.com/Lruihao/FixIt/commit/636968214a494b749b63958403801e112949d1ab) 运行`npm run server:production`，我在本地测试是可以的

**Comment by iuvhub** [comment]
> > 好像这个灯箱不起作用
> 
> 你切到这个分支 ([6369682](https://github.com/Lruihao/FixIt/commit/636968214a494b749b63958403801e112949d1ab)) 运行`npm run server:production`，我在本地测试是可以的
> 
> <img alt="image" width="970" src="https://user-images.githubusercontent.com/33419593/153133710-bd5aacb7-5aac-4857-a515-7a1932ccb505.png">

![image](https://user-images.githubusercontent.com/89133723/153135887-70e8a228-a745-4a49-bc60-41435fa2f83a.png)
k'y可以通过控制台获取该字段吗

**Comment by iuvhub** [comment]
> > > 好像这个灯箱不起作用
> > 
> > 
> > 你切到这个分支 ([6369682](https://github.com/Lruihao/FixIt/commit/636968214a494b749b63958403801e112949d1ab)) 运行`npm run server:production`，我在本地测试是可以的
> > <img alt="image" width="970" src="https://user-images.githubusercontent.com/33419593/153133710-bd5aacb7-5aac-4857-a515-7a1932ccb505.png">
> 
> ![image](https://user-images.githubusercontent.com/89133723/153135887-70e8a228-a745-4a49-bc60-41435fa2f83a.png) k'y可以通过控制台获取该字段吗

![image](https://user-images.githubusercontent.com/89133723/153136136-413ff9aa-d3c6-41e4-bdba-c3a0b4f85fe3.png)
我设置了呀

**Comment by Lruihao** [comment]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/33419593/153136503-124832a3-5115-4067-a6f7-e7ef13a3fece.png">

控制台可以获取，或许你应该刷新缓存

<img width="680" alt="image" src="https://user-images.githubusercontent.com/33419593/153136716-bacd6d7f-9e9a-41d8-8709-f3e24f8e3da7.png">

**Comment by iuvhub** [comment]
> <img alt="image" width="724" src="https://user-images.githubusercontent.com/33419593/153136503-124832a3-5115-4067-a6f7-e7ef13a3fece.png">
> 
> 控制台可以获取，或许你应该刷新缓存
> 
> <img alt="image" width="680" src="https://user-images.githubusercontent.com/33419593/153136716-bacd6d7f-9e9a-41d8-8709-f3e24f8e3da7.png">

![image](https://user-images.githubusercontent.com/89133723/153138518-5e67fa22-26e9-4c13-ae4c-7454c00c7dbf.png)
我该sendbtn的值起作用，但是灯箱的还是没有获取到，我是用github page来部署的

**Comment by iuvhub** [comment]
我把子模块删除了重新添加，报未定义的错
![image](https://user-images.githubusercontent.com/89133723/153699662-4d9f9b00-ce3c-41c9-967a-09b3bed67180.png)

**Comment by iuvhub** [comment]
> 我把子模块删除了重新添加，报未定义的错 ![image](https://user-images.githubusercontent.com/89133723/153699662-4d9f9b00-ce3c-41c9-967a-09b3bed67180.png)

![image](https://user-images.githubusercontent.com/89133723/153699706-57b87f6e-4a90-485e-93d9-64e5a94890e5.png)

**Comment by iuvhub** [comment]
> > 我把子模块删除了重新添加，报未定义的错 ![image](https://user-images.githubusercontent.com/89133723/153699662-4d9f9b00-ce3c-41c9-967a-09b3bed67180.png)
> 
> ![image](https://user-images.githubusercontent.com/89133723/153699706-57b87f6e-4a90-485e-93d9-64e5a94890e5.png)

![image](https://user-images.githubusercontent.com/89133723/153699888-a0005f64-7b4a-4653-b132-3b081aa8f3fa.png)
但是这个页面又可以正常显示

**Comment by Lruihao** [comment]
params.page.lightgallery 打开了吗

**Comment by iuvhub** [comment]
> params.page.lightgallery 打开了吗

打开了，手机上是正常的，我换个浏览器看看，缓存我也清楚了

**Comment by iuvhub** [comment]
> params.page.lightgallery 打开了吗

现在又可以了，请问文章里的照片是否也支持灯箱

**Comment by Lruihao** [comment]
> 现在又可以了，请问文章里的照片是否也支持灯箱

支持，详细看主题文档
```
![img alt](http://xx.img "img title")
```

**Comment by iuvhub** [comment]
> > 现在又可以了，请问文章里的照片是否也支持灯箱
> 
> 支持，详细看主题文档
> 
> ```
> ![img alt](http://xx.img "img title")
> ```

谢谢
