### ISSUE TITLE
[BUG] Simple typo (en) 

### ISSUE THREAD

**Issue by darrenaddy** [Lruihao/FixIt#60]
你好
谢谢你的这个项目！

Nǐ hǎo
xièxiè nǐ de zhège xiàngmù!

### Describe the bug 描述你遇到的错误
Simple (english) typo (misspelling): discription should be: description

I'm sorry but I don't really understand how to use GIT properly yet, or I would have contributed the fix.
I just did a simple Search/Replace with a text editor on the entire theme/hugo site.

Feature Request: Is there an easy way to make the pages PRINT (on paper) well? Right now, I get the top navigation bar repeating itself and blocking page content (that should be printed) behind it. I find this is a problem on a LOT of Hugo-generated sites. I understand that it is not a Hugo-specific problem, but more a CSS issue.

You may see this yourself if you try to print out a page, such as the theme-documentation-extended-shortcodes/ page.

**Comment by Lruihao** [comment]
Thanks for your bug reports! @darrenaddy
