### ISSUE TITLE
[FEATURE] add pageStyle option

### ISSUE THREAD

**Issue by sexdev** [Lruihao/FixIt#62]
### Describe the feature you want 描述你的功能需求

- Feature 1 功能需求 1
  我希望能够控制网页的文章和图片的空间占比，现在的网页文章和功能图片只占据屏幕的中间一部分，大部分空间是浪费的。能够做成左右两栏也行。最好有自己能够控制的配置。
谢谢！

**Comment by dipperkun** [comment]
期待实现该功能！对于宽屏显示器，确实浪费了很多空间！可以设置一个参数控制文档占宽比

**Comment by Lruihao** [comment]
可以暂时在 `_custom.scss` 修改 css 样式

.page {
    width: 56%; // 修改宽度
  }

v0.2.13 会做调整

**Comment by Lruihao** [comment]
require https://github.com/Lruihao/FixIt/issues/65

**Comment by Lruihao** [comment]
v0.2.13 已处理，[预览文档](https://fixit-1vj5p4qii-lruihao.vercel.app/theme-documentation-basics/#site-configuration)

**Comment by Lruihao** [comment]
- [pageStyle文档](https://fixit.lruihao.cn/theme-documentation-basics/#page-style)
- #80
