### ISSUE TITLE
source map not found

### ISSUE THREAD

**Issue by selfhostportal** [Lruihao/FixIt#67]
### Describe the bug 描述你遇到的错误
DevTools 无法加载来源映射：无法加载 https://xxxxxxxx.xxx/sm/5d8a97cdb40a6c49031b52d63494a6eca084416b5b035e5698fdc5fa0969b2c3.map 的内容：HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE

一段简短的对于你遇到的错误的描述.
请问是哪里设置导致会GET请求无法存在map资源？
我网上搜索了一下所示编译过程的中间产物，但我对前端不了解。
请问又遇到过吗？

### Expected behavior 期待的行为
Chrome控制台不在报错

一段简短的对于你期待的行为的描述.

### Screenshots 屏幕截图

如果可以的话, 提供屏幕截图对解决问题很有帮助.

### Build Environment 构建环境

- OS: [Ubuntu]
- Theme version/commit [e.g. 0.2.0, 2ccba79]
- Hugo version [hugo v0.92.2-CDF6A0D6+extended linux/amd64 BuildDate=2022-02-11T14:17:39Z VendorInfo=gohugoio]

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

### Preview Environment 预览环境

- OS: [Windows 11]
- Browser [Chrome]

### Additional Information 补充信息

Configuration files or front matter code...
配置文件或者前置参数的代码...

**Comment by Lruihao** [comment]
你好，可以提供一下控制台报错的截图吗

**Comment by Lruihao** [comment]
> 不是不蒜子统计的问题，我说的就是警告哪行，FireFox倒是没有。
> 
> 我网上搜索了一下所示编译过程的中间产物，但我对前端不了解。
> 
> 我也不明白是什么组件会请求这个？

如果用 cdn 没有问题的话，我猜大概了引用了其他插件的压缩文件，但是没有引用其 map 文件导致的，有空我再仔细研究一下。

**Comment by Lruihao** [comment]
http://www.ruanyifeng.com/blog/2013/01/javascript_source_map.html

**Comment by selfhostportal** [comment]
关闭了启用CSS源代码映射就没有警告了。
关闭了启用JavaScript源代码映射，还是显示告警。
一开始我以为是JavaScript的锅，想不到是CSS文件的。
那么问题来了，怎么知道是哪一个CSS文件源代码没有生成映射？
以及怎么修改对应映射路径文件呢？老是请求到https://xx.xx/sm/xxxx.map路径.
虽然可以创建对应目录下的空白文件来应付请求404的错误，但是没有根本解决问题。

**Comment by Lruihao** [comment]
> 关闭了启用CSS源代码映射就没有警告了。
> 
> 关闭了启用JavaScript源代码映射，还是显示告警。
> 
> 一开始我以为是JavaScript的锅，想不到是CSS文件的。
> 
> 那么问题来了，怎么知道是哪一个CSS文件源代码没有生成映射？
> 
> 以及怎么修改对应映射路径文件呢？老是请求到https://xx.xx/sm/xxxx.map路径.
> 
> 虽然可以创建对应目录下的空白文件来应付请求404的错误，但是没有根本解决问题。

我觉得作为依赖插件，本主题不需要debug他们的代码，所以我打算引用没有map的压缩文件，使用主题的用户则无需手动处理。

**Comment by Lruihao** [comment]
已处理，[Preview](https://fixit-q5dmw7mnq-lruihao.vercel.app/)
