### ISSUE TITLE
[BUG] pwa resource 404 error

### ISSUE THREAD

**Issue by xinx1n** [Lruihao/FixIt#87]
### Describe the bug 描述你遇到的错误

开启 pwa 请求的文件路径不对，service worker 的请求文件的路径是不是写死了。
按照[文档](https://fixit.lruihao.cn/zh-cn/pwa-support/)的流程走完了，不知道是应该修改文档的步骤还是修改 service worker 的内容？

### Screenshots 屏幕截图

<img width="1633" alt="image" src="https://user-images.githubusercontent.com/16302191/159664597-fbb7c944-8ab1-4840-b25f-b086afcb5a02.png">

<img width="1626" alt="image" src="https://user-images.githubusercontent.com/16302191/159664558-f565f761-5f3b-4680-a58e-cdcc619e40c8.png">

### Preview Environment 预览环境

macOS 12
edge

**Comment by Lruihao** [comment]
`/js/theme.min.js` 的路径没有错，service worker 写的相对路径，你打开 chrome://serviceworker-internals/?devtools 试试把  service worker 注销看看。

**Comment by xinx1n** [comment]
> 

刚我又重新 build 了下，对应的文件是在的，路径也对，就是不知道为什么 404，然后直接从地址栏打开对应的 url 也是 404，我先自己排查下原因吧~
